export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_TOKEN = 'CHANGE_TOKEN';
export const VERIFY_PHONE = 'VERIFY_PHONE';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const CHANGE_ADMIN_DATA = 'CHANGE_ADMIN_DATA';
export const CHANGE_CLIENT_DATA = 'CHANGE_CLIENT_DATA';
export const CHANGE_CLIENT_SERVICE_DATA = 'CHANGE_CLIENT_SERVICE_DATA';
export const CHANGE_SERVICE_DATA = 'CHANGE_SERVICE_DATA';
